name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  testing:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Build the binary
        run: make

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Run tests
        run: |
          chmod +x prepare-testing.sh
          ./prepare-testing.sh
          chmod +x test.py
          ./test.py replay test.list
          rm -rf __tests__

  build_and_release:
    name: Build and Create Release
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Build the binary
        run: make release

      - name: Create tar.gz archives dynamically
        run: |
          name="${GITHUB_REPOSITORY#*/}"
          for dir in build/*; do
            if [ -d "$dir" ]; then
              base_name=$(basename "$dir")
              # Create tar.gz archive for the 'gmmf' binary and include LICENSE and README.md
              tar -czf "build/${name}-${base_name}.tar.gz" -C "$dir" gmmf -C ../.. LICENSE README.md
              echo "Created archive: build/${name}-${base_name}.tar.gz"
            fi
          done

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes \
              build/*.tar.gz
